### ISSUE TITLE
An error occurred. Please start Anki while...

### ISSUE THREAD

**Issue by JSY88** [kelciour/awesometts-anki-addon#1]
First of all, thank you for the cool stuff!
It worked well for a while, and suddenly there was an error like this.
What can I do to fix this?
--------------------------------------
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.9 (ae67c976) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 7
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\jinsub\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 298, in accept
    self._accept_next()
  File "C:\Users\jinsub\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 403, in _accept_next
    note=note)
  File "C:\Users\jinsub\AppData\Roaming\Anki2\addons21\814349176\awesometts\router.py", line 439, in __call__
    callbacks['fail'](exception)
  File "C:\Users\jinsub\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\generator.py", line 358, in fail
    message = exception.message
<class 'AttributeError'>: 'ValueError' object has no attribute 'message'

**Comment by kelciour** [comment]
I've added a quick fix to fix this exception message. Unfortunately, it won't solve the original problem, but at least, the next time when this happens, the error message will be different.
Please use Anki - Tools - Add-ons - Check for Updates to update the add-on.

**Comment by JSY88** [comment]
The error message has changed!
It will no longer terminate with an error.
thanks a lot!

**Comment by kelciour** [comment]
Ah, no problem. I'm closing this issue then.
