### ISSUE TITLE
Error when I am trying to record

### ISSUE THREAD

**Issue by anandrajput116** [kelciour/awesometts-anki-addon#13]
Hey  there I am getting this error when I am trying to record 
403 client error forbidden

**Comment by kelciour** [comment]
I guess, you created your own API key but haven't enabled the Text-to-Speech API for your project. Try to use your key with this link https://texttospeech.googleapis.com/v1beta1/voices?key=API_KEY to get a bit more information about the error or use this link from https://stackoverflow.com/a/50784790 to enable the Text-to-Speech API - https://console.cloud.google.com/flows/enableapi?apiid=texttospeech.googleapis.com

**Comment by anandrajput116** [comment]
Thank you, sir, for your help. My issue is resolved.
