### ISSUE TITLE
Update to Anki 2.1.20beta7; AwesomeTTS Failed to Load

### ISSUE THREAD

**Issue by CanDKD** [kelciour/awesometts-anki-addon#15]
AwesomeTTS Google Cloud TTS (unofficial) loaded with an earlier beta version of Anki 2.1.20 but failed to load after I upgraded to beta7.  Here is a screenshot of the error message:

![Awesome TTS Problem](https://user-images.githubusercontent.com/4369080/73614209-41e54700-45ba-11ea-9303-9507574c045d.jpg)

**Comment by kelciour** [comment]
Thanks! It's been fixed.

**Comment by CanDKD** [comment]
Thank you for your quick response.  I very much appreciate that you are maintaining AwesomeTTS.
