### ISSUE TITLE
Oxford Dictionary : Incorrect MIME Type

### ISSUE THREAD

**Issue by AntoineQ1** [kelciour/awesometts-anki-addon#20]
Hello,
I have opened an issue on the main page of the add-on, but since I am using your version, here is a copy of the problem. _(original version: https://github.com/AwesomeTTS/awesometts-anki-addon/issues/82)_
**Context :** 
Anki 2.1 with AwesomeTTS (latest version) and Oxford Dicitonary as source.
**What happens :**
`"Cannot preview the input phrase with these settings. Request got audio/mpeg Content-Type for web request; wanted binary/octet-stream"`
**How to correct it:**
> 
> 
> 
> 
> Issue solved :
> Please replace `require=dict(mime='binary/octet-stream', size=1024),` to `require=dict(mime='audio/mpeg', size=1024),` in 814349176\awesometts\service\oxford.py
> 
> I started a pull request : #90
> > Ok, I arrived on the software a week ago, I didn't even know Anki 2.0 ;-)
> > > A fairly simple and universal way is to go to the list of plugins, choose AwesomeTTS and click on Show Files.
> > > Or you can manually search in **%appdata%**.
> > > For example, the path may be : **C:\Users{YOUR_USERNAME}\AppData\Roaming\Anki2\addons21\814349176\awesometts\service**
> > 
> > 
> > Tell me if it works for you !
> 
> OH MY GOD, you saved my life. At first, I barely believe that it will work, but for now it works well. Thank you very much!!! <3
> 
> I will attach some Screenshots in case someone low tech needs them:
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/9654732/79044453-68b1a080-7c2f-11ea-8915-8151f6e5808a.jpg)
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/9654732/79044436-5899c100-7c2f-11ea-871b-d6e1235568a3.jpg)
Screenshots by @liwenjing93 (https://github.com/liwenjing93), method by myself

To conclude, it's a fix that only takes 30 seconds, and is very useful ! Thanks

**Comment by kelciour** [comment]
Thank you!
