### ISSUE TITLE
Anki 2.1.26 is putting a progress bar on the top of our progress bar

### ISSUE THREAD

**Issue by evandrocoan** [kelciour/awesometts-anki-addon#21]
The problem with this second bar anki puts is that it does not allow to interact it our progress bar and hit the cancel button (and neither we can close the progress bar anki puts up).

![image](https://user-images.githubusercontent.com/5332158/81626421-0684c080-93d2-11ea-8e6b-e61497d031ae.png)

**Comment by kelciour** [comment]
Thanks for letting me know about it. It might take a week or two before I can look and do something about it.

**Comment by evandrocoan** [comment]
I just fixed it. But if found another bug on Anki which I am working on first. Later I will open pull-requests here and on Anki fixing things.

**Comment by kelciour** [comment]
That'd be great and very much appreciated!

ср, 13 мая 2020 г. в 01:23, evandrocoan <notifications@github.com>:
