### ISSUE TITLE
Can't generate audio or listen a preview

### ISSUE THREAD

**Issue by Malakian75s** [kelciour/awesometts-anki-addon#26]
Hi, After the update (May 19th) I'm not able to generate an audio or listen a preview.

![image](https://user-images.githubusercontent.com/8305645/82400048-02812000-9a1c-11ea-9866-e7efd68a2bd3.png)

**Comment by evandrocoan** [comment]
Can you confirm whether the directory `awesometts\\.cache` exists and you can access it?

**Comment by Malakian75s** [comment]
This path exist C:\Users\Carlos_Sardina\AppData\Roaming\Anki2\addons21\814349176\awesometts\.cache

but is empty

**Comment by evandrocoan** [comment]
Try deleting it.

**Comment by Malakian75s** [comment]
It works! thanks.
