### ISSUE TITLE
I got the error when trying to insert TTS tag.

### ISSUE THREAD

**Issue by vhung85** [kelciour/awesometts-anki-addon#3]
When I click to insert, I got this error.
The anki version is: 2.1.11 (3cf770c7)
The AwesomeTTS version is: v1.13.0-dev

Thank you so much

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.11 (3cf770c7) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\hungl\AppData\Roaming\Anki2\addons21\814349176\awesometts\gui\templater.py", line 201, in accept
    tform = self._card_layout.tab['tform']
<class 'AttributeError'>: 'CardLayout' object has no attribute 'tab'

![image](https://user-images.githubusercontent.com/10986604/56046386-50354e80-5d6d-11e9-90af-461a0661072f.png)

**Comment by Uitalo** [comment]
I have the same error:
Debug info:
Anki 2.1.11 (3cf770c7) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.3
Flags: frz=True ao=True sv=2
Add-ons possibly involved: AwesomeTTS Google Cloud Text-to-Speech unofficial
Caught exception:
  File "/Users/cassiouitalo/Library/Application Support/Anki2/addons21/814349176/awesometts/gui/templater.py", line 201, in accept
    tform = self._card_layout.tab['tform']
<class 'AttributeError'>: 'CardLayout' object has no attribute 'tab'

**Comment by thiagopikcius** [comment]
I have the same error. 
Everything works fine if I'm using AwesomeTTS in the browser (Add TTS Audio to Selected Notes).
<img width="540" alt="Screenshot 2019-04-17 16 37 22" src="https://user-images.githubusercontent.com/18253597/56315866-4164e800-612f-11e9-8125-5b05e6c9a37a.png">

But it doesn't work in a template (Add TTS On-The-Fly Tag to Template)
![image](https://user-images.githubusercontent.com/18253597/56315964-84bf5680-612f-11e9-9b9c-444da47817b3.png)

When trying to insert the TTS tag to template, I get the following error
![image](https://user-images.githubusercontent.com/18253597/56316003-9d2f7100-612f-11e9-9c16-fa9485208db6.png)

**Comment by danicraft4343** [comment]
i have the same issue. i only need on-the-fly, but it´s not working
