### ISSUE TITLE
New user - 403 Client Error 

### ISSUE THREAD

**Issue by Mahalom07** [kelciour/awesometts-anki-addon#31]
Hello - I am new to anki and honestly know little about coding.  I followed the instructions to add AwesomeTTS, added my API key, though when I go to preview the add-on and change configuring service to google cloud-to-text speech, I get this error:

403 Client Error: Forbidden for url: https://texttospeech.googleapis.com/v1/text:synthesize?key=[REDACTED]

If I use google translate I have no problem running it - though the voice associated w google voice is intolerable.  (I don't think it makes a difference because it happens in both languages, but I am using Anki and the TTS for Japanese studies.)

Can anyone help me figure out how to get this add-on working properly?  It'd be a huge help.

Thanks so much!

**Comment by kelciour** [comment]
Sorry, the instructions on the add-on page doesn't seem to mention it, but you need to enable the Cloud Text-to-Speech API before you can use it with your API key,

> To enable an API for a project using the console:

> 1. Go to the Cloud Console API Library - [https://console.cloud.google.com/apis/library?project=_](https://console.cloud.google.com/apis/library?project=_)
> 2. From the projects list, select a project or create a new one.
> 3. In the API Library, select the API you want to enable. If you need help finding the API, use the search field and/or the filters.
> 4. On the API page, click ENABLE.

https://cloud.google.com/apis/docs/getting-started#enabling_apis

**Comment by Mahalom07** [comment]
Took a few additional steps, but got it figured out and works perfectly.
Thank you so much, this will be a huge help to my studies!

All the best, and thank you for such a great add-on.

Very Respectfully,
Josh

**Comment by kelciour** [comment]
Great! As an additional step, maybe consider to limit the current API key to certain IP addresses or deleting it and making a new one, since it's been posted online alongside with the error message and was compromised.

https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key
