### ISSUE TITLE
Support of the new Google cloud for Anki 2.0.x

### ISSUE THREAD

**Issue by Aakasan** [kelciour/awesometts-anki-addon#4]
I noticed the 2.1 got an unofficial Google Cloud Text-to-Speech add-on. Would it be possible to add support for 2.0.x as well? 
 Many of the japanese voices (like Naver)  have stopped working (request got text/html- or something)  and the remaining ones sound like robots. 

There are also many important add-ons that don't have 2.1 support yet

**Comment by SpaceLens** [comment]
I gotta agree. The WaveNet add-on is incredible for assisting some people in pronunciation. While it sounds robotic at times, its still saying the word right.

**Comment by kelciour** [comment]
I guess it can be closed now.

As possible alternatives, there's CCBC (https://github.com/lovac42/CCBC + https://github.com/lovac42/awesometts-CCBC-addon) and Anki 2.1.20 has built-in TTS support now too.

> Changes in 2.1.20beta3 (95b497cc)
> You can now use {{tts en_US:Field}} on your card templates to use the text to speech support built into Windows and macOS, changing the language code as necessary.

https://apps.ankiweb.net/docs/beta.html
