### ISSUE TITLE
When trying to add On-The-Fly TTS tag to template I get this exception (has no attribute 'front')

### ISSUE THREAD

**Issue by jaredagordon** [kelciour/awesometts-anki-addon#40]
When attempting to use the on-the-fly feature I get this:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.30 (06a69c25) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-18 13:32:26
Add-ons possibly involved: ⁨AwesomeTTS⁩

Caught exception:
Traceback (most recent call last):
  File "..../Library/Application Support/Anki2/addons21/awesometts/awesometts/gui/templater.py", line 205, in accept
    target = getattr(tform, now['templater_target'])
AttributeError: 'Ui_Form' object has no attribute 'front'

This is what a front template looks like:
![image](https://user-images.githubusercontent.com/60485584/90630477-15f48080-e1ef-11ea-82bc-fc5237231d12.png)

**Comment by kelciour** [comment]
Hi! Thank you for letting me know about it!

I'm sorry but it's unlikely will be fixed anytime soon. At the moment I'm not interested to spend time on the add-on and it might take months before I'll get back to it.

I'd suggest to post it on https://github.com/AwesomeTTS/awesometts-anki-addon/issues, maybe it'll be fixed or someone will send a pull request with a fix and then switch to https://ankiweb.net/shared/info/1436550454 or install it from https://github.com/AwesomeTTS/awesometts-anki-addon/releases/

As a possible workaround, maybe create a new preset and add it manually using something like `<tts preset="..." hidden>{{Front}}</tts>`.

> If you want to use a Preset for on-the-fly feedback, you can use the preset attribute, e.g.: `<tts preset="My eSpeak Preset">apple</tts>`

https://ankiatts.appspot.com/usage/on-the-fly

![S43SrWHu55](https://user-images.githubusercontent.com/16260735/90640220-647a3d00-e238-11ea-9367-c9fd0af97cff.gif)
