### ISSUE TITLE
Audio not working with "type in answer" cards.

### ISSUE THREAD

**Issue by tinypepa** [kelciour/awesometts-anki-addon#45]
I'm new to Anki (so please forgive my ignorance) and was very happy to discover AwesomeTTS recently so I can quickly add audio to my cards. Adding audio to cards ("Basic" type) worked, but I wanted to go a step further by changing the card type to "Type in answer". Then the audio stopped working, both on my desktop (Mac) and iPhone app. I saw a suggestion on Reddit to create a third field (called "Audio") and put the audio link there, so I did that, but with no results. I even tried deleting my cards, importing the file again, adding the third "audio" field, and then adding the audio (Source field is "Back", Destination field is "Audio"). Autoplay audio is on.

I know audio can work with the "type in answer" cards, because that's how the WaniKani Japanese deck I downloaded works... what am I doing wrong? :(

**Comment by kelciour** [comment]
Click on Cards... and add something like this to the Back Template.

```
<div><br></div>
<div>{{Audio}}</div>
```

> Card templates tell Anki which fields should appear on the front and back of your card, and control which cards will be generated when certain fields have text in them. By adjusting your card templates, you can alter the design and styling of many of your cards at once.

https://docs.ankiweb.net/#/templates/intro?id=card-templates

![image](https://user-images.githubusercontent.com/16260735/104450093-a1144f80-55b0-11eb-8d9f-70522750b412.png)

**Comment by kelciour** [comment]
You're welcome :)
