### ISSUE TITLE
SpanishDict seems to have slower audio

### ISSUE THREAD

**Issue by kodovanie** [kelciour/awesometts-anki-addon#46]
Hi all, I used awesometts to add audio to my spanish vocabulary. I have not used awesometts for a couple of weeks/montsh (for Spanish words). Now I realized that when I create sounds for my words, the voice seems to be slower (when comparing it with sounds I created in the past). It was a little bit quicker. I am using still the same SpanishDict, voice Spanish (es), because I liked the sounds, accents etc. I am not sure if it is only the use with the male voice or also with the female voice. However I cannot change between male and female voice.

Is it possible for me to make audio a little bit faster? Or have there been any changes to SpanishDict?

I am using Anki 2.1.35, awesometts 1.29.0

Thank you all for your help!

**Comment by kelciour** [comment]
Could you attach or upload somewhere two audio files with the words that were used to download them? The one that is a little bit quicker and the slow one.

This way I could compare them with https://audio1.spanishdict.com/audio?lang=es&text=cuadrado to see if they're the same or different.

**Comment by kodovanie** [comment]
Hi, thanks for your reply.

As an example, I am sending you two sounds for the same word - "trabajos". The new one with longer file name is quicker. I put them into zip file so that I could attach it here.

IMHO I believe the "issue" is only with this male voice in the instances when you do not have a word in its most basic form (e.g. trabajo), but in some "other-extended form" (e. g. trabajos)?

[trabajos.zip](https://github.com/kelciour/awesometts-anki-addon/files/5859817/trabajos.zip)

**Comment by kelciour** [comment]
Thank you for the sample files! It's indeed slower than before.

![audacity_wSOZ4a2lUT](https://user-images.githubusercontent.com/16260735/105617040-e88aaf00-5dec-11eb-8efa-e4749afbc5f4.png)

And the slower version is the same version that could be found on SpanishDict now.

![firefox_7qEml9RgOa](https://user-images.githubusercontent.com/16260735/105617933-77022f00-5df3-11eb-94e2-168fe811fd94.png)

![firefox_ijAd61w3nW](https://user-images.githubusercontent.com/16260735/105617079-69e24180-5ded-11eb-8c51-5b11a01eb234.png)

It looks like this audio file was generated using Text-to-Speech. I guess, SpanishDict changed something on their end and I don't see how I can fix it.

I can only suggest to delete such audio files and replace them with the audio file downloaded from Forvo, Google Translate or maybe Microsoft Azure Text to Speech.

Demo - https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/

This version of the AwesomeTTS add-on doesn't support Microsoft Azure. I made the first working version for English a few months ago and intended to return to the AwesomeTTS before the new year, fix a few minor bugs, add support for all languages and update the add-on on AnkiWeb, but got busy and it didn't happen. But https://ankiweb.net/shared/info/1436550454 should already support Microsoft Azure.

Microsoft Azure requires the API key and has a free tier of 0.5 million characters free per month after creating an accout using a non-virtual credit card.

https://azure.microsoft.com/en-us/pricing/details/cognitive-services/speech-services/

https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Microsoft-Azure-Text-to-Speech#key-creation

I'll close it, but feel free to comment if you have any questions or if I missed something.
