### ISSUE TITLE
Error where trying to add the add-on

### ISSUE THREAD

**Issue by Agnollo** [kelciour/awesometts-anki-addon#48]
I'm trying to install the add-on but I'm getting the below error message:

One or more error occurred:
814349176: Please check your internet connection.
HTTPSConnetionPool(host='ankiweb.net',port=443):Max retries exceeded with url:/shared/download/814349176?v=2.1&p=42 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))

<img width="376" alt="Anki issue" src="https://user-images.githubusercontent.com/81639589/113022087-864f8100-9184-11eb-81ec-f4a9466b1f50.PNG">

**Comment by kelciour** [comment]
If it still happens, maybe try to disable VPN or proxy.

The add-on could be installed manually by using [this link](https://ankiweb.net/shared/download/814349176?v=2.1&p=42) to download it as .zip archive, then go to Anki - Tools - Add-ons - View Files to open the "Anki2\addons21" folder, create a new subfolder "814349176" and unzip `__init__.py` and everything else into that folder. Then restart Anki.
