### ISSUE TITLE
Bing voice

### ISSUE THREAD

**Issue by omega3** [kelciour/awesometts-anki-addon#5]
Can you work on or contribute to adding Bing voice to awesometts-anki-addon?
https://github.com/AwesomeTTS/awesometts-anki-addon/issues/71

**Comment by kelciour** [comment]
As for now, I can only fix some issues related to Google Cloud Text-to-Speech sometime later.

It's still possible for me to do it or probably anything else, but I can only do it on commission or pay what you want. Though it may take some time if I'm too busy doing something else.

**Comment by omega3** [comment]
Bing has changed its API. Only 30 free trial is available now. So, you may close it as invalid.
