### ISSUE TITLE
Forvo

### ISSUE THREAD

**Issue by tkleinschmidt90** [kelciour/awesometts-anki-addon#53]
I can't find Forvo in the newer versions, is it not longer supported?

**Comment by kelciour** [comment]
At the moment, aside from Google and Azure, it's unlikely something else will be added or fixed.

I think, AwesomeTTS - Add speech to your flashcards - https://ankiweb.net/shared/info/1436550454 - supports Forvo using a paid API key - https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Forvo-Pronunciation-Dictionary

There's also a few Forvo add-ons listed on AnkiWeb - https://ankiweb.net/shared/info/858591644 and https://ankiweb.net/shared/info/560814150

**Comment by tkleinschmidt90** [comment]
Thank you for your reply! I have a paid API key for Forvo and I can use it on my old notebook with Anki Version 2.1.33 and AwesomeTTS v1.24.0. Now I bought a new one and downloaded newer versions of these apps and Forvo doesn't appear in the list of available services anymore.

**Comment by kelciour** [comment]
I've no idea why it does't appear in the list anymore, but since it's about https://ankiweb.net/shared/info/1436550454 it'd be better to ask Luc about it, maybe by creating a new issue at https://github.com/AwesomeTTS/awesometts-anki-addon/issues
