### ISSUE TITLE
Any way to add Sanskrit TTS ?

### ISSUE THREAD

**Issue by asphoa** [kelciour/awesometts-anki-addon#55]
I come across this Sanskrit TTS. I know nothing about code, but just am wondering if there is any way to add it into your AwesomeTTS? It would be great for me as a SKT student.,

https://github.com/avinashvarna/sanskrit_tts
https://pypi.org/project/sanskrit-tts/

**Comment by kelciour** [comment]
It's possible, but at the moment I have no much interest to support or add any new services and can suggest to ask Luc about it by creating a new issue at https://github.com/AwesomeTTS/awesometts-anki-addon/issues

**Comment by asphoa** [comment]
Thanks for responding, kelciour! I will transfer the suggestion there.
