### ISSUE TITLE
Cannot preview the input phrase with these settings. set-cookie

### ISSUE THREAD

**Issue by Noah23234** [kelciour/awesometts-anki-addon#59]
This problem has been happening to me for a few days and I don't know how to solve it.
![set-cookie](https://user-images.githubusercontent.com/93730427/140388060-41263970-da1d-4740-b021-2ffcc8407620.jpeg)

**Comment by kelciour** [comment]
The service works for me. If you used it a lot, maybe Google shows the captcha now or temporarily banned your IP address, maybe for a few hours, and no longer returns the audio file. Maybe as alternative try to use built-in on-the-fly TTS - https://docs.ankiweb.net/templates/fields.html#text-to-speech

**Comment by Noah23234** [comment]
@kelciour I'm using anki to study and I use AwesomeTTS every day... I just tried it and it worked perfectly (I didn't need to do anything). Thanks :)
