### ISSUE TITLE
Google Cloud Text - Vietnamese Voice missing

### ISSUE THREAD

**Issue by trevdoggo** [kelciour/awesometts-anki-addon#6]
Hi there, first of all THANK you so much for all of your hard work in putting AwesomeTTS together and adding Google Cloud Text to this add-on.

My issue: Hoping to use the Vietnamese (Tiếng Việt) voice which is available from the Google Cloud Text site. However in AwesomeTTS this voice does not appear. Is there any possible way to fix this?

Thank you again.

**Comment by kelciour** [comment]
Thank you for the report. I've updated the hardcoded list of supported voices and reuploaded the add-on on AnkiWeb.

**Comment by trevdoggo** [comment]
Man, you are actually amazing. Thank you so much.

**Comment by kelciour** [comment]
Thanks! It didn't take much time and it was easier to do it sooner than some time later.
