### ISSUE TITLE
will you merge back to AwesomeTTS/awesometts-anki-addon ?

### ISSUE THREAD

**Issue by lucwastiaux** [kelciour/awesometts-anki-addon#8]
Will the google cloud text-to-speech functionality be merged back to AwesomeTTS/awesometts-anki-addon ? the maintainer here has mentioned he is willing to merge pull requests: https://github.com/AwesomeTTS/awesometts-anki-addon/issues/69

**Comment by kelciour** [comment]
Sorry for the very late reply. I've finally sent a pull request - https://github.com/AwesomeTTS/awesometts-anki-addon/pull/87 - and I'm closing this issue.
